<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>CaribWeather Alert</title>
</head>
<body style="font-family: Arial, sans-serif; color: #0f172a; line-height: 1.6;">
  <h1 style="color: #0f3b57;">CaribWeather Alert</h1>
  <p>{{ $alertMessage }}</p>
  <table cellpadding="8" cellspacing="0" style="border-collapse: collapse; border: 1px solid #dbeafe;">
    <tr><th align="left">Type</th><td>{{ $alert->type }}</td></tr>
    <tr><th align="left">Location</th><td>{{ $alert->location }}</td></tr>
    <tr><th align="left">Threshold</th><td>{{ $alert->threshold ?? 'Default threshold' }}</td></tr>
    <tr><th align="left">Time</th><td>{{ now()->format('M j, Y g:i A') }}</td></tr>
  </table>
  <p style="font-size: 12px; color: #475569;">This alert was generated by CaribWeather.</p>
</body>
</html>
